### PR TITLE
Rename SyntheticClone to Synthetic

### PR DESCRIPTION
**Pull request by WilczynskiT**
Related to #287

Rename `SyntheticClone` to `Synthetic`.

### CODE REVIEW

**Comment by syall** [comment]
Needs references of `SyntheticClone` in aws/aws-sdk-go-v2 to be updated before merging this PR.

**Review by syall — APPROVED** [review]
Looks like all of the references to `SyntheticClone` have been renamed.

**Comment by WilczynskiT** [comment]
@syall Why the merge is impossible? I see the info: "cannot merge this time".
Will you do the merge?

**Comment by syall** [comment]
Hi @WilczynskiT!

The merge needs to be planned with the change in aws/aws-sdk-go-v2#1966, otherwise aws-sdk-go-v2 will fail to compile.

The AWS SDK Go team will take on the task of orchestrating the merges between repositories.

**Pull request merged**
